
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM openjdk:8
EXPOSE 8000
ADD target/miumg-api-homework.jar miumg-api-homework.jar 
ENTRYPOINT ["java","-jar","/miumg-api-homework.jar"]
